Restart ovpn warning
NethServer/nethserver-openvpn pull request #68
Opened 2020-05-26 14:10 UTC by andre8244

- Clear pending changes to RoadWarrior accounts on OpenVPN service start
- `nethserver-vpn-save` event is refactored and replaced by `nethserver-openvpn-save` event

https://github.com/NethServer/dev/issues/6177

2020-05-26 15:39 UTC, gsanchietti reviewed
Rename `nethserver-openvpn-certificates-otp` to `nethserver-openvpn-otp` and move at position 20 or 30 inside the creatlinks.

Also 40 or 50 is good.

2020-05-26 16:01 UTC, gsanchietti requested changes

2020-05-26 16:01 UTC, gsanchietti commented on createlinks
> +    'nethserver-openvpn-otp' => ' 20',
```suggestion
    'nethserver-openvpn-otp' => '20',
```

2020-05-26 16:01 UTC, gsanchietti commented on createlinks
> +    'nethserver-openvpn-otp' => ' 20',
Suggested change will  fix the build

2020-05-27 06:20 UTC, gsanchietti approved these changes

2020-05-27 07:21 UTC, edospadoni approved these changes

2020-05-27 08:40 UTC, merged